import { injectable } from 'tsyringe';
import { ReportCatalogItem } from './ReportingTypes';

const CATALOG: ReportCatalogItem[] = [
  {
    id: 'sales-by-customer-detail',
    label: 'Sales by Customer Detail',
    description: 'Invoice-like bookings, customer payments, and credit memo rows grouped by customer.',
    category: 'Sales',
    route: '/reports/sales-by-customer-detail',
    endpoint: '/reports/sales-by-customer-detail',
  },
  {
    id: 'customer-balance-detail',
    label: 'Customer Balance Detail',
    description: 'Chronological debit/credit movement and running customer balance.',
    category: 'Customers',
    route: '/reports/customer-balance-detail',
    endpoint: '/reports/customer-balance-detail',
  },
  {
    id: 'customer-payment-details',
    label: 'Customer Payment Details',
    description: 'Customer-side payment register with receipt references and booking linkage.',
    category: 'Customers',
    route: '/reports/customer-payment-details',
    endpoint: '/reports/customer-payment-details',
  },
  {
    id: 'payment-details-by-customer',
    label: 'Payment Details by Customer',
    description: 'Alternate customer payment-detail view using the same receivable/refund transaction truth.',
    category: 'Customers',
    route: '/reports/payment-details-by-customer',
    endpoint: '/reports/payment-details-by-customer',
  },
  {
    id: 'customer-ledger',
    label: 'Customer Ledger',
    description: 'Opening, in-period entries, and closing balance statement for customers.',
    category: 'Customers',
    route: '/reports/customer-ledger',
    endpoint: '/reports/customer-ledger',
  },
  {
    id: 'invoice-credit-note-list-by-date',
    label: 'Invoice And Credit Note List by Date',
    description: 'Date-ordered invoice-like booking rows and credit memo entries.',
    category: 'Sales',
    route: '/reports/invoice-credit-note-list-by-date',
    endpoint: '/reports/invoice-credit-note-list-by-date',
  },
  {
    id: 'invoice-list',
    label: 'Invoice List',
    description: 'Flat invoice-style list from bookings with paid and due amounts.',
    category: 'Sales',
    route: '/reports/invoice-list',
    endpoint: '/reports/invoice-list',
  },
  {
    id: 'invoices-by-month',
    label: 'Invoices by Month',
    description: 'Monthly aggregated booking invoice value with paid and due totals.',
    category: 'Sales',
    route: '/reports/invoices-by-month',
    endpoint: '/reports/invoices-by-month',
  },
  {
    id: 'sales-by-product-service-detail',
    label: 'Sales by Product/Service Detail',
    description: 'Booking sales detail grouped by derived service labels.',
    category: 'Sales',
    route: '/reports/sales-by-product-service-detail',
    endpoint: '/reports/sales-by-product-service-detail',
  },
  {
    id: 'transaction-list-by-customer',
    label: 'Transaction List by Customer',
    description: 'Dense customer-wise transaction timeline across invoices, payments, and credits.',
    category: 'Transactions',
    route: '/reports/transaction-list-by-customer',
    endpoint: '/reports/transaction-list-by-customer',
  },
  {
    id: 'transaction-list-by-date',
    label: 'Transaction List by Date',
    description: 'Chronological register of customer-facing transactions.',
    category: 'Transactions',
    route: '/reports/transaction-list-by-date',
    endpoint: '/reports/transaction-list-by-date',
  },
  {
    id: 'payment-splits-by-customer',
    label: 'Transaction List with Splits for Customer Payment Details',
    description: 'Truthful one-payment-to-one-booking split rows, future-ready for true split allocations.',
    category: 'Transactions',
    route: '/reports/payment-splits-by-customer',
    endpoint: '/reports/payment-splits-by-customer',
  },
  {
    id: 'vendor-ledger',
    label: 'Vendor Ledger',
    description: 'Vendor expense and inbound refund running balance report.',
    category: 'Vendors',
    route: '/reports/vendor-ledger',
    endpoint: '/reports/vendor-ledger',
  },
  {
    id: 'outstanding-payments',
    label: 'Outstanding Payments',
    description: 'Booking due amount register for pending receivables.',
    category: 'Transactions',
    route: '/reports/outstanding-payments',
    endpoint: '/reports/outstanding-payments',
  },
  {
    id: 'monthly-income-expense',
    label: 'Monthly Income vs Expense',
    description: 'Month-wise summary of invoiced, received, expense, and refund values.',
    category: 'Transactions',
    route: '/reports/monthly-income-expense',
    endpoint: '/reports/monthly-income-expense',
  },
  {
    id: 'refund-register',
    label: 'Refund Register',
    description: 'Outbound and inbound refund register with direction markers.',
    category: 'Refunds',
    route: '/reports/refund-register',
    endpoint: '/reports/refund-register',
  },
  {
    id: 'booking-register',
    label: 'Booking Register',
    description: 'Booking-centric commercial register with status and due context.',
    category: 'Transactions',
    route: '/reports/booking-register',
    endpoint: '/reports/booking-register',
  },
  {
    id: 'gst-view',
    label: 'GST / Tax View (Derived)',
    description: 'Derived tax-oriented snapshot with explicit schema limitations.',
    category: 'Transactions',
    route: '/reports/gst-view',
    endpoint: '/reports/gst-view',
    experimental: true,
  },
  {
    id: 'customer-report-existing',
    label: 'Customer Report',
    description: 'Existing customer report endpoint and behavior retained.',
    category: 'Existing',
    route: '/customers/report',
    existing: true,
  },
  {
    id: 'vendor-report-existing',
    label: 'Vendor Report',
    description: 'Existing vendor report endpoint and behavior retained.',
    category: 'Existing',
    route: '/vendors/report',
    existing: true,
  },
];

@injectable()
export class GetReportCatalog {
  execute(): ReportCatalogItem[] {
    return CATALOG;
  }
}
